kv_namespaces = [
  {binding = "REDIRECTS", id = "d5ece11a6c3b412498fbc0571000126c", preview_id = "e3a16a7517114c5eb486335c37c8170a"},
]
name = "shorten"
routes = ["kuy.sh/*", "www.kuy.sh/*"]
type = "webpack"
webpack_config = "webpack.config.js"
